const TODOS_GETLIST = 'TODOS/GET_LIST'

const TODOS_ADDTODO = 'TODOS/ADD_TODO'

const TODOS_CHANGEDONE = 'TODOS/CHANGE_DONE'

const TODOS_DELETETODO = 'TODOS/DELETE_TODO'

const TODOS_CHANGENAME = 'TODOS/CHANGE_NAME'

const TODOS_CLEARTODOS = 'TODOS/CLEAR_TODOS'

const TODOS_CHANGEALL = 'TODOS/CHANGE_ALL'

const FILTERTYPE_CHANGETYPE = 'FILTER/CHANGE_TYPE'

export {
  TODOS_ADDTODO,
  TODOS_GETLIST,
  TODOS_CHANGEDONE,
  TODOS_DELETETODO,
  TODOS_CHANGENAME,
  TODOS_CLEARTODOS,
  TODOS_CHANGEALL,
  FILTERTYPE_CHANGETYPE,
}
